import image1 from '../images/1.png';
import image2 from '../images/2.png';
import image3 from '../images/3.png';
import image4 from '../images/4.png';
import image5 from '../images/5.png';
import image6 from '../images/6.png';
import image7 from '../images/7.png';
import image8 from '../images/8.png';
import image9 from '../images/9.png';
import image10 from '../images/10.png';
import image11 from '../images/11.png';
import image12 from '../images/12.png';

export const MAIN_MOVIES = [
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2010',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image1,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image1,
    movieId: 1,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2011',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image2,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image2,
    owner: '1',
    movieId: 2,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2012',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image3,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image3,
    owner: '1',
    movieId: 3,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: true,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2010',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image4,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image4,
    movieId: 4,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2011',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image5,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image5,
    owner: '1',
    movieId: 5,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: true,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2012',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image6,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image6,
    owner: '1',
    movieId: 6,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2010',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image7,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image7,
    movieId: 7,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2011',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image8,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image8,
    owner: '1',
    movieId: 8,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2012',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image9,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image9,
    owner: '1',
    movieId: 9,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2010',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image10,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image10,
    movieId: 10,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: true,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2011',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image11,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image11,
    owner: '1',
    movieId: 11,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2012',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image12,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image12,
    owner: '1',
    movieId: 12,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2010',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image1,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image1,
    movieId: 13,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2011',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image2,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image2,
    owner: '1',
    movieId: 14,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2012',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image3,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image3,
    owner: '1',
    movieId: 15,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: false,
  },
];

export const SAVED_MOVIES = [
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2010',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image1,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image1,
    movieId: 16,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: true,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2011',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image2,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image2,
    owner: '1',
    movieId: 17,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: true,
  },
  {
    country: 'США',
    director: 'К. Ноланд',
    duration: 107,
    year: '2012',
    description: 'Ноланд гений (почти как Кодзима)',
    image: image3,
    trailerLink: 'https://kinopoisk.ru',
    thumbnail: image3,
    owner: '1',
    movieId: 18,
    nameRU: '33 слова о дизайне',
    nameEN: '33 words about design',
    isSaved: true,
  },
];
